### ISSUE TITLE
Immersive Travel

### ISSUE THREAD

**Issue by rfuzzo** [rfuzzo/tes3-mods#7]
## Todos
- [ ] Sway
- [ ] Bob (not sure yet)
- [ ] Both together: simulate walking

## Epics
- [ ] dynamic striders on the routes
- [ ] walking on actual terrain (raycast? terrain hight? water?)

## Routes
- [ ] SN - BM
- [ ] etc
